@echo off
echo Starting MediAlert SMA v2.0...
echo ================================

echo Activating virtual environment...
call .venv\Scripts\activate.bat

echo Setting Python path...
set PYTHONPATH=.

echo Starting Flask application...
python run.py